### ISSUE TITLE
iPad2,1 on iOS 9.3.2 - Build not working

### ISSUE THREAD

**Issue by ZawacchiRSX** [ganoninc/trident-kloader-updated#1]
Installed the compiled app on my iPad 2,1 using Cydia Impactor, opened the app and tapped Start. Nothing happens except the button greying out, and the words "Waiti Exec Sleep Mode" do not appear.

**Comment by ganoninc** [comment]
Can you read "w00t roo" at the bottom of the screen?

**Comment by ZawacchiRSX** [comment]
I was unable to get the IPA to work; however I managed to install using my Mac and Xcode and it worked out in the end. Thanks for the reply!

**Comment by ganoninc** [comment]
I don't have a paid developer account so I followed this method to build the IPA: http://stackoverflow.com/questions/35403969/how-to-create-ipa-without-apple-developer-progromammer-in-xcode7

Maybe it can explain your difficulties. I'd like to know if the IPA worked for someone.

**Comment by zheungyik** [comment]
Junmatsuzawa, Can you upload your ipa which is compiled on Xcode somewhere?

**Comment by ZawacchiRSX** [comment]
I also do not have a registered dev account, so I ran the app directly from Xcode to my iPad. I have attached a compiled .ipa file (made using the same method as @ganoninc), but I'm not sure it will work.


[Trident-junmatsuzawa.ipa.zip](https://github.com/ganoninc/trident-kloader-updated/files/688519/Trident-junmatsuzawa.ipa.zip)

**Comment by zacharyreese** [comment]
^^^ Dude your ipa worked! Successfully on iOS 6 now!!! Thank you!!!!!!!!

**Comment by Sagobird** [comment]
How Long did you guys wait when "w00t roo" is on the screen?

**Comment by ganoninc** [comment]
@junmatsuzawa I moved your IPAD into the build directory and mentioned your help in the file name and in the README.

Thank you

**Comment by ZawacchiRSX** [comment]
No problem, glad I could help!

@Sagobird, it took about 10 to 15 seconds for me.

**Comment by ganoninc** [comment]
@junmatsuzawa Could you compile this new version (1.2)? Thank you!

**Comment by ZawacchiRSX** [comment]
Here is the compiled .ipa for version 1.2:

[Trident-Kloader-1.2-compiled-by-junmatsuzawa.ipa.zip](https://github.com/ganoninc/trident-kloader-updated/files/691923/Trident-Kloader-1.2-compiled-by-junmatsuzawa.ipa.zip)
