### ISSUE TITLE
Support for iPod 5 on 9.3.1

### ISSUE THREAD

**Issue by Moose23** [ganoninc/trident-kloader-updated#16]
Is this possible? I've heard the keys haven't been found/released but I'd really appreciate it if you could add support for this, thanks!

**Comment by Xernium** [comment]
depends on if you want to test some experimental versions :P
Yes there are no keys but that doesn't mean we cant support it, it will just take some trial and error

**Comment by Moose23** [comment]
I'd be happy to help, unless there's a large chance for a brick, and I'm not very good with software and hardware stuff, but I can try :P

**Comment by Xernium** [comment]
no chance for a brick, worst case is the device will crash and reboot (kernel panic)

**Comment by Moose23** [comment]
That's good, I'll be available to help when you get to the iPod 5, just write me a message or something

**Comment by Xernium** [comment]
Actually hold on 5 min ill push something experimental for you, tell me if it works

**Comment by Xernium** [comment]
[experimental_t+k.ipa.zip](https://github.com/ganoninc/trident-kloader-updated/files/706954/experimental_t.k.ipa.zip)

Youll need Cydia impactor to install it

**Comment by Xernium** [comment]
and unzip that file to get the ipa

**Comment by Moose23** [comment]
Ok, I hit start and got a horizontal green line and w00t root
E: it disappeared, but the w00t root still is there

**Comment by ganoninc** [comment]
It seems that your experimental version works.

**Comment by Moose23** [comment]
If you don't mind asking, how would I go downgrading from here? Would I need SHSH blobs for the version I want to go to?

**Comment by ganoninc** [comment]
You'll need the SHSH blobs of your device for the iOS version you target.

**Comment by Moose23** [comment]
Well, don't have any blobs at all, but I'm happy I could test that for you on my device
