### ISSUE TITLE
Support for iPhone 5,2 (iOS 9.2.1)

### ISSUE THREAD

**Issue by aarons2222** [ganoninc/trident-kloader-updated#17]
Will this device be supported....

**Comment by Xernium** [comment]
if you want to try out a beta build, I don't have a device to test it on.
Badest thing that can happen if it fails, is that the device straight up reboots

**Comment by Xernium** [comment]
Try this experimental build https://github.com/ganoninc/trident-kloader-updated/files/706954/experimental_t.k.ipa.zip <- Unzip the file to get the ipa
You'll need Cydia Impactor to install it.

**Comment by Xernium** [comment]
has already been done, closing this retroactively
