### ISSUE TITLE
iPad 2,2 - iOS 9.3.4 Stuck at w00t root

### ISSUE THREAD

**Issue by braltan** [ganoninc/trident-kloader-updated#18]
I installed latest Trident + Kloader 1.2.2 on my iPad 2,2 pressed start, green lines appeared right side of the screen and at the bottom w00t root goes gray than nothing happens. I tried restarting the device but nothing happens no cydia pls help..

**Comment by ganoninc** [comment]
It's not supposed to install cydia. You can downgrade your iPad to iOS 6.1.3 with that. 

Green lines are the sign that it works. So if you wish to downgrade, follow the instructions of the repo's README

**Comment by braltan** [comment]
Yeah i noticed that after some research. And now i succesfully downgraded to iOS 6.1.3 thank you for your help. Also a full tutorial might be good for people who couldn't understand the steps it took me 2-3 hours in order to understand what i need to do.
