### ISSUE TITLE
Not working iPad 2,1 9.3.3

### ISSUE THREAD

**Issue by zacharyreese** [ganoninc/trident-kloader-updated#2]
Same issue as the guy above, Start button goes grey and freezes from there.

**Comment by ganoninc** [comment]
Can you read "w00t roo" at the bottom of the screen?

**Comment by Xernium** [comment]
Are you running the latest build? If not try the latest version which can be found here:
https://github.com/ganoninc/trident-kloader-updated/blob/master/build/Trident%2Bkloader%201.2.1.ipa

If you still experience the issues please send me a screenshot
Does it say iPad2,1 iOS 9.3.3 at the bottom of the screen in the app?
