### ISSUE TITLE
iPhone 4s IOS 9.3.2

### ISSUE THREAD

**Issue by Crastokieran** [ganoninc/trident-kloader-updated#20]
PLEASE Reply...
Will it work on iPhone 4s ios 9.3.2 as it was getting stuck if we would tap root and nothing would happen.
please fix this and let me know about it.I was waiting since a year please fix it.

**Comment by iTommy258** [comment]
Do you get the "woot root" sign? If yes, lock the device and follow the steps from readme.md . If you need any further help, feel free to ask, I already downgraded my iPhone4,1 from iOS 9.3.2 to iOS 6.1.3.

**Comment by Crastokieran** [comment]
It Worked For Me Thank YOU
got it woot root!!!!!

**Comment by Crastokieran** [comment]
thank you for the reply

**Comment by Xernium** [comment]
Thanks @iTommy258 
- Report closed -
