### ISSUE TITLE
Support iPhone 5,3 on 9.3.4

### ISSUE THREAD

**Issue by itsCozmikk** [ganoninc/trident-kloader-updated#23]
Someone has already gotten the Tident app compiled and it seems to work here: https://app.box.com/s/2vid1yhiutrw155sismltq2mpc83l5nq
His reddit is: https://www.reddit.com/user/mehulrao

**Comment by jake5253** [comment]
Tried on my iPhone5,3 (N49AP). Still says not supported.

**Comment by Xernium** [comment]
Trident+Kloader is not just simply Trident.
Since we implement kloader, the entire thing behaves a little different so that doesn't help us sadly.

**Comment by iTommy258** [comment]
Thats what my iPhone 5 (supported) gave out from the Trident mentioned above: http://pastebin.com/97A54cTy

**Comment by itsCozmikk** [comment]
@Djsn0wfall Is there still being work done for the 5,3 on 9.3.4?

**Comment by Xernium** [comment]
Yes but since I have some real-life issues atm I can't contribute further as of now

**Comment by itsCozmikk** [comment]
It's okay. I understand. I appreciate the hard work and how much you contribute to the community. I hope you will be able to work on it again soon. :+1:

**Comment by Xernium** [comment]
Closing this retroactively because support has been added.
