### ISSUE TITLE
Support ipod 5,1 for ios 9.0.2

### ISSUE THREAD

**Issue by Chasewhip8** [ganoninc/trident-kloader-updated#24]
Add support for ipod 5,1 for all ios 9 versions if possible

**Comment by iTommy258** [comment]
I am not sure if Trident works on iOS 9.x below iOS 9.2.1. Maybe wait until a real Developer of this project answers your question. For any "User Level" question, feel free to ask me.

**Comment by Xernium** [comment]
Trident as of yet only works with iOS 9.1-9.3.4
If you have 9.0.2- 9.1 you can jailbreak untethered using pangu http://en.9.pangu.io  

As for other iOS 9 versions, I am working on them but there are issues past 9.3 atm so please have a little patience, thanks!

**Comment by Chasewhip8** [comment]
Well that sucks. I am on 9.3.3 and trident still won't even work on my iPad 5,1. It said unsupported ios device. But you clearly star that you support it.

**Comment by angelparedesr1** [comment]
How  Cain I install the tools for Windows??

**Comment by Xernium** [comment]
We support the iPod5,1 to a certain extent, ans will more in the future, however that does not include the iPad5,1
