### ISSUE TITLE
iPhone5,3 no support on 9.3.1 

### ISSUE THREAD

**Issue by jake5253** [ganoninc/trident-kloader-updated#25]
Is there a particular reason 9.3.1 cannot be supported? 
Special Note: I'm okay with using Impactor and trying beta builds

**Comment by Xernium** [comment]
Trident-Kloader is here for downgrading, not jailbreaking, with that said we are having some issues with task for pid execution, but sadly I don't have time to look into that atm.

I will push beta builds when I have time to do so, thanks for your patience

**Comment by jake5253** [comment]
I understand, please note that 9.3.1 is not jailbreak-able (its a 32-bit device) so I was attempting to downgrade =]
