### ISSUE TITLE
Error ipad2,1 ios 9.3.2 dowgrade to 6.1.3

### ISSUE THREAD

**Issue by javier6d2** [ganoninc/trident-kloader-updated#27]
Hi folks

Everything is going well, but after put the Ipad 2 (9.3.2) on sleep model, I execute the command with Odysseus OTA:
idevicerestore -e iPad2,1_6.1.3_10B329_Restore.ipsw
And I receive the error shown below:

Found device in DFU mode
Identified device as iPad2,1
Extracting BuildManifest from IPSW
Product Version: 6.1.3
Product Build: 10B329 Major: 10
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 1035088774031
Getting ApNonce in dfu mode... 57 2a 79 0b 6f ed 77 cd ed e7 a9 94 2b db eb 83 dd c8 15 49
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode...
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
ERROR: Unable to send TSS request
ERROR: Unable to get SHSH blobs for this device

I have repeat the process with another laptop but I get the same error.

It's possible to fix?

Kind regards.

**Comment by iTommy258** [comment]
Hello, it's definitely something with your device. Do you try it on Mac or windows?
I used a modified ipsw to downgrade my iPad2,2 and my iPhone4,1. I am not sure if that is the solution but it's worth a try. 

Alternative solutions:

Use another cable
Download another stock ipsw
Recheck your iPad components

Useful things to know: 
Came your iPad with iOS5?
Do you try it on Mac or windows?


I hope I can help your with that. I am not a Dev here but I would call myself as a first aid men for user level questions at this project. Please try the solutions and answer my questions. Keep in mind that you have to be very carefully to don't brick your device, because it will probably never see iOS 6 again if you restore it to iOS 9.3.5!

Good luck!

**Comment by Xernium** [comment]
# Step 1: Custom And decrypted IPSW File
To create one open the Terminal / CMD and enter: 
`./ipsw iPad2,1_6.1.3_10B329_Restore.ipsw downgrade.ipsw -memory`  
If you are on Mac OS or
`ipsw.exe iPad2,1_6.1.3_10B329_Restore.ipsw downgrade.ipsw -memory`  
If you're on windows
##### NOTE: The `-memory` parameter is optional and will just speed the creation up if you have a decent computer

# Step 2: Download OTA-SHSH Blob files
While your device is plugged into the computer do:
`./idevicerestore -t downgrade.ipsw `  
If you are on Mac OS or
`idevicerestore.exe -t downgrade.ipsw `
If you're on windows

If it returns:
`ERROR: Unable to send TSS request`
`ERROR: Unable to get SHSH blobs for this device`
in the terminal do **NOT** continue

### Important! On OSX do now `killall iTunesHelper`
#### !!! Put your device in kDFU mode now !!!

# Step 3: Restore the device! 
If you've gotten to this point congratulations! If anything following this point fails you will have to restore to the latest unjailbreakable firmware! Be warned!
While your device is plugged in and in kDFU mode do:

To execute the downgrade on OS X do:
`./idevicerestore -w downgrade.ipsw`
On Windows:
`idevicerestore.exe -w downgrade.ipsw`  

## Tampering with the device at this point will result in the restore failing and you having to upgrade to the latest unjailbreakable version!!!

Now hope and pray ...!
Anything else?  :P

**Comment by javier6d2** [comment]
Thank you for your answers :)

I´m on windows10, when I execute on cmd:

ipsw.exe iPad2,1_6.1.3_10B329_Restore.ipsw downgrade.ipsw -memory

After several lines I get this error:
.
.
.
run 4253: start=1114898432 sectors=320, length=163840, fileOffset=0x2fde1250
run 4255: start=1115073536 sectors=1, length=178, fileOffset=0x2fe09250
Growing root to minimum: 18446744070477582336
Cannot shrink volume

I have tried to decrypt another firm (iPad2,1_8.1_12B410) but the ipsw.exe crashes after 10 sec. Only complete a few steps:
ipsw.exe iPad2,1_8.1_12B410_Restore.ipsw downgrade.ipsw -memory

Hashing IPSW...
Matching IPSW in FirmwareBundles/... (4ad4aa64...)
checking: FirmwareBundles/\Down_iPad2,1_6.1.3_10B329.bundle\Info.plist
checking: FirmwareBundles/\Down_iPad2,2_6.1.3_10B329.bundle\Info.plist
and crash

There is anything else I could do?

**Comment by javier6d2** [comment]
Solved, yihaaaa :)))))

After de problema with the ipsw.exe, I customized the firmware with Beehind v0.5 Beta software, after that I used the command:

idevicerestore -e iPad2,1_6.1.3_10B329_Restore.ipsw

And voila!!

Thank you very much!

I used this versión to odysseusota: 
https://github.com/Sn0wCooder/odysseusota-windows
