### ISSUE TITLE
The updated ipa doesn't work on iPad 2,1

### ISSUE THREAD

**Issue by zheungyik** [ganoninc/trident-kloader-updated#3]
I have the same problem

**Comment by ganoninc** [comment]
Can you read "w00t roo" at the bottom of the screen?

**Comment by zheungyik** [comment]
I don't have w00t roo at the bottom of the screen.

**Comment by ganoninc** [comment]
Do you have a mac with Xcode? 

I'd like to know if the only the IPA doesn't work for you or if the whole project freezes.

Thanks

**Comment by zheungyik** [comment]
I have Xcode 3 on my snow leopard and don't have developer account

**Comment by ganoninc** [comment]
I will try to generate different IPA this evening, May I contact you for testing?

**Comment by zheungyik** [comment]
Sure

**Comment by zheungyik** [comment]
Sure, My email is zheungyik@me.com

**Comment by ganoninc** [comment]
Check out the new IPA made by @junmatsuzawa here: https://github.com/ganoninc/trident-kloader-updated/tree/master/build

**Comment by mattargithub** [comment]
Can you send ipa for ipad2 wifi  ios 9.3.4(13G35)
Model MC979HN/A
My email add is matta.ravi@yahoo.com

**Comment by ganoninc** [comment]
I asked @junmatsuzawa to compile a new IPA. I'll let you know when it's done.

**Comment by Xernium** [comment]
Anyway if your iPhone model is iPad2,4 it would be useless, no keys for that device at all, converging with Jonathan seals to get some atm

**Comment by Xernium** [comment]
# Attention!  
The newest build fixes the issue on 9.3.4 and pre 9.3 versions!  
It can be found here:  
https://github.com/ganoninc/trident-kloader-updated/blob/master/build/Trident%2Bkloader%201.2.1.ipa  
As always you need Cydia Impactor to install it, which can be found here:   
http://www.cydiaimpactor.com

Let me know if there are any problems with it

**Comment by mattargithub** [comment]
Thanks
