### ISSUE TITLE
Ipad 2 9.1 support?

### ISSUE THREAD

**Issue by buyinginquiries** [ganoninc/trident-kloader-updated#33]
Hi, was wondering with the additional offsets being released, can this  version and model number make it into the IPA? thanks!

**Comment by buyinginquiries** [comment]
Specifically A1395. Thanks!

**Comment by ganoninc** [comment]
Code updated :) 

Now we need to find someone to compile an IPA.

**Comment by Xernium** [comment]
ill do that in a few min

**Comment by Xernium** [comment]
https://github.com/ganoninc/trident-kloader-updated/blob/master/build/Trident%2Bkloader%201.2.3.ipa

**Comment by buyinginquiries** [comment]
I'm trying this on an iPad2 Wi-Fi, the iPad just reboots without stating
anything. I think the offsets might be wrong.

**Comment by buyinginquiries** [comment]
Hmm.. not sure what the issue is, I think one of the offset's are wrong for 9.1 version.

**Comment by ganoninc** [comment]
If this is the case, please open an issue here: https://github.com/benjamin-42/Trident/issues

**Comment by buyinginquiries** [comment]
Posted, thanks!
