### ISSUE TITLE
How can I do the process in Windows?

### ISSUE THREAD

**Issue by angelparedesr1** [ganoninc/trident-kloader-updated#42]
Please , I have a doubt. I install the trident in my dispositive, I,ve been trying to do it with libimobiledevice but it doesn't works. Please help me.

**Comment by EGYbkgo9449** [comment]
1. Download the IPA from the build folder.
2. Download Cydia Impactor (cydiaimpactor.com)
3. Connect your device to your PC via USB.
4. Drag the IPA to Cydia Impactor then enter your Apple ID email and password.
5. Trust the profile in your device.
6. Enjoy 😄

**Comment by angelparedesr1** [comment]
No, I need to to know I can downgrade with this program, no how to install it

**Comment by EGYbkgo9449** [comment]
Follow this tutorial:

https://www.reddit.com/r/jailbreak/comments/5lakuy/tutorial_easy_downgrade_for_iphone_4s_from_933_to/
