### ISSUE TITLE
i got shsh blobs from version 9.3.5 will that do??

### ISSUE THREAD

**Issue by deus187** [ganoninc/trident-kloader-updated#43]
ipad mini (iPad2,5 P105AP IOS 9.3.2)

**Comment by deus187** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>@ServerVersion</key>
	<string>2.1.0</string>
	<key>APTicket</key>
	<data>
	MIIKqDALBgkqhkiG9w0BAQUxggK0gQgqLRgu+wIAAIIEQokAAIMECgAAAIQEAQAAAIUE
	AQAAAIYRaUJvb3QtMjgxNy42MC4yfjKHFJutko3kFe5cn4Im1lMBqujXIRrhiBRgWPyX
	xtVNfVIXiX0feR/yMHOQe4kUgj/WytR+XSsib1VEwd3DoKyLb0OKFP01tFMyBTystpjZ
	HpkiSeUpSp2rjRS8hpgyB80YZo/nRIz3kazDogmGNo4Uhse+siAJ8MBcAdpKqoCwlKd+
	omCPFFY/DnaAe0Cg6kBWJj0w/gtAwC76kBTA/8DQnt5Qw65+6nx/88SoX4LBpJIU9czg
	XoGpvi72bsKH9pL/3yCxOGCUEWlCb290LTI4MTcuNjAuMn4ylhFpQm9vdC0yODE3LjYw
	LjJ+MpcUYFj8l8bVTX1SF4l9H3kf8jBzkHuYFII/1srUfl0rIm9VRMHdw6Csi29DmRT9
	NbRTMgU8rLaY2R6ZIknlKUqdq5oUhVKlMWfb1mRXHwczCAvvL7CWtGWcFAt98wpAsnQJ
	9sV04SJ0oLgBW3MxnzAEAQAAAJ8xBAEAAACfMgQBAAAAnzMEAQAAAJ82BAEAAACfNwQB
	AAAAnzgEAQAAAJ85BAEAAACfOwQBAAAAnzwEAQAAAJ89BAEAAACfPgQBAAAAn0sU0eeD
	pR1rR4TNfZJmRBm7bama7DGfThTjwNOlfHqcu6lFsbMF+3InUN6FQp9PFHvXgJf95t0y
	edYuZF2kH2r5BHhbn1AUKrqcjAsfDqgWxVUFRBL9GimUVlafVAQBAAAAn1UEAQAAAJ9W
	BAEAAACfgWQUNFA8VSoLz1XOCJS8mzC/lqDuCrufgWUUyk/fH1Mg25742Jha6s7OoURU
	DoyfgWYUoeC8uP6UgFCb7e3RgBQWj2Yf3MefgWcEAQAAAJ+BaAQBAAAAn4FpBAEAAAAE
	gYAz4cNHImArf/9sBvuZt8aZbo0+JnisQPKCtnKfL0oJWRV2Iwxx+Jgzv9vxbGnZBNLh
	gnnVOMK4LFR7j8TMIRxaTqpSpohJmkGefhmwSHQSYOziOSrcZ0D8USqIOrup9RYsfpq4
	N/gKnZyQG9RxqIiXadgSzWvZqVROndIqRBoWeaGCB1wwggP4MIIC4KADAgECAgEQMA0G
	CSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYw
	JAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBw
	bGUgUm9vdCBDQTAeFw0wNzAxMDUxOTIxNTlaFw0yMjAxMDUxOTIxNTlaMH4xCzAJBgNV
	BAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZp
	Y2F0aW9uIEF1dGhvcml0eTEyMDAGA1UEAxMpQXBwbGUgU2VjdXJlIEJvb3QgQ2VydGlm
	aWNhdGlvbiBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD+
	8t3aZTmwcuMDhIH0VsnRoUq7yAQB80YNleE3lQppR8bEjHk+R1UGsgYU636k9SP+QjWY
	7zQFzprTrZTQog/C0rQESEwjWlvHC51i0/PjaxD+lwhXxhJ2dxmyxsMsmO23KYfk3Bi2
	5fO6E/uytrdn2cvfb6WTPe16k2e0/TQW5ACrC7dOH1rWA2g+crYUMDoMZJegRiJ5G3cs
	Wy6Q4BHcFqPhyPeEsk/cSzoK1RJ+3BE/+hFzZRpJcKB+dYK0PCsvVd8wiLF1TUXcBygt
	SjqF/Z+VPiK6nEb3t2h7s5TVQj4Fszj4Z3lIjGwfi77u7VQF1aMLWH14DySpodwKdOr3
	AgMBAAGjgZwwgZkwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
	BBYEFEk9NlPJ1xXhhmFOrKurGFZjXcPGMB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm
	90dNfwheMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly93d3cuYXBwbGUuY29tL2FwcGxl
	Y2Evcm9vdC5jcmwwDQYJKoZIhvcNAQEFBQADggEBADTFDMUOWREvpsKfMnjnZDJp263C
	Jcq3R4O3kjxxU6CyrTCVgFC9bV9M3M54DUxJEFA4EDW/RYGsZlgsISP4ll6A6dPGTP2F
	rjlh9iiqRO0Vmz9HwFesZxyMzdSTjU/balSne0JbD5nG1zirUqehgx2FMHTqDR3aaISP
	4oR+y7lBbtWfqEK1/zO2cX/qo7ndSQNghXYQPo6o4TbjEt2FbO1mU7BbSJsvf/bKHPBd
	mC10rfBIR8XhmmeyIg+wDgKg4bpqYrm0tXH0JeGz5aDtyBpAtfgxFQWkXDgjTJCdRwOA
	gNQykEWPD6+b/ALu7cvmMfafFeZ9K1dDDuIPoaCtidowggNcMIICRKADAgECAgIBeDAN
	BgkqhkiG9w0BAQUFADB+MQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEm
	MCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxMjAwBgNVBAMTKUFw
	cGxlIFNlY3VyZSBCb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTExMDcyNzIw
	MzIwOFoXDTIxMDcyNzIwMzIwOFowYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxl
	IEluYy4xDDAKBgNVBAsTA0VUUzEwMC4GA1UEAxMnSDRBLURhcndpbi1Qcm9kLUNFUE8w
	LVRpY2tldC1EYXRhQ2VudGVyMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCJrrSN
	rn5c5A2hsarX2zkd0kMjndLJXLIQ6h19hxRXMIiE5bTcpaVbrUMS1B8FjvZ3zkZzzzE3
	0hXJeIIrY1qfybZNwEF4YMwXCEZvTTe+hJ+muTEYYw+gJHaLYtpzHOQ9T9jCNHwYNAfc
	uzqxilidiz5Re0hNVBAtrohj4AJy3QIDAQABo4GDMIGAMAsGA1UdDwQEAwIHgDAdBgNV
	HQ4EFgQUmaE60CXdC35VKCIqsdhW6f5y2U4wHwYDVR0jBBgwFoAUST02U8nXFeGGYU6s
	q6sYVmNdw8YwMQYKKoZIhvdjZAYBCwEB/wQgMB6hHDEaggRCiQAAhAQBAAAAhQQBAAAA
	n4FrBAEAAAAwDQYJKoZIhvcNAQEFBQADggEBAAgETxCf0LtZjT6ewIryIx3t4pueEKM4
	fceo5zSbK9Z3gqrE6fixLEc2LiPdmvLEIDmmftHIxR2CFNIt43VmgZQE6b9bie43++b7
	C9EIw/95Y/s6qnBCSbKmKlicvMvMI3U0C/T2jQ61TECQAFrGxM9tzoBMjzo1Zoxfair4
	BC9ZisCRWIgH48Lmikcniz1vw+I/mLPbuz6cEyvE6Y0jQc3TgA4r7j855aCRR6Wy9x4f
	HLz7wOj9aA7FOxEam4z8UdM7pWLEsDHo1Dk3LYkTQo1ZrSlPlQbjv8SwdoKwJ2E6cUlW
	fgl5UZF1k/eSVMb3SwI0veoA1GvgyipF0ow5s7M=
	</data>
	<key>LLB</key>
	<dict>
		<key>Blob</key>
		<data>
		RElDRUAAAAAIAAAAKi0YLvsCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAEhTSFOMAAAAgAAAAFPp4oqwOh35G5KQB72Z
		Ua3Y7MuOrhjB7rsKQh4sjvRY/F2ny/MF8p4W9EO8k2I32MEwOS/NA8lNPc8h
		PDYQ42XXZpfuXluMTlX4t5K7DcYUB9VMX/voO61MTm16pO9XuLH5qTmqqfdE
		1fjfA50S4V+aZrmkE+KS7E5BubH2kJ9z
		</data>
		<key>PartialDigest</key>
		<data>
		QAAAAHhRAgDzNxqr2uHE1iyRuZ/qy2VS24UBjg==
		</data>
	</dict>
	<key>iBSS</key>
	<dict>
		<key>Blob</key>
		<data>
		RElDRUAAAAAIAAAAKi0YLvsCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAEhTSFOMAAAAgAAAAFG/KzDtaqKoV+ISrrQ5
		QHhy//+k+Il/+VQf7No2+jrLVoBniwAHGJdhrdFu8YS7GU/UFuEJQ7EAqWh6
		BLaYn1f11bGTp5olOX+NcDpK2mt9PNgZ5Px3x7uH935cqoHdRqqWLEODFjYr
		NRkeDcwEg7piqbNHIUf/P+Cnik3HgFv+
		</data>
		<key>PartialDigest</key>
		<data>
		QAAAAHhRAgDzNxqr2uHE1iyRuZ/qy2VS24UBjg==
		</data>
	</dict>
</dict>
</plist>

**Comment by deus187** [comment]
..gonna be not the right version, i think.. but not laugh at least i'm trying..

**Comment by ganoninc** [comment]
What's your device and iOS version?

**Comment by deus187** [comment]
Romain Giovanetti schreef op 2017-01-28 08:01: 

> What's your
device and iOS version? 
> 
> --
> You are receiving this because you
authored the thread.
> Reply to this email directly, view it on GitHub
[1], or mute the thread [2].

ActivationState
Activated
ActivationStateAcknowledged true
BasebandStatus
NoTelephonyCapabilty
BluetoothAddress xxxxxxxxxxxx
BoardId 10
BrickState
false
BuildVersion 13F69
CPUArchitecture armv7f
ChipID 35138
DeviceClass
iPad
DeviceColor black
DeviceName ios
DieID
xxxxxxxxxxxxxxxxxxxxxx
EthernetAddress xxxxxxxxxxxxxxx
FirmwareVersion
iBoot-2817.50.3
HardwareModel P105AP
HardwarePlatform
s5l8942x
HostAttached true
MLBSerialNumber xxxxxxxxxxxxxxxxx
ModelNumber
MF432
PartitionType 
PasswordProtected true
ProductName iPhone
OS
ProductType iPad2,5
ProductVersion 9.3.2
ProductionSOC
true
ProtocolVersion 2
RegionInfo NF/A
SIMStatus
kCTSIMSupportSIMStatusReady
SerialNumber
xxxxxxxxxxxxxxxx
SoftwareBundleVersion 
TelephonyCapability
false
TimeIntervalSince1970 xxxxxxxxxxxxxxxxxxxx
TimeZone
Europe/Amsterdam
TimeZoneOffsetFromUTC 3600.000000
TrustedHostAttached
true
UniqueChipID xxxxxxxxxxxxxxxxxxxx
UniqueDeviceID
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
UseRaptorCerts
true
Uses24HourClock false
WiFiAddress
xxxxxxxxxxxxxxxxxxxx
WirelessBoardSerialNumber
xxxxxxxxxxxxxxxxxxx
iTunesHasConnected true

here you go.... 
--


---------------------------------------------- DISCLAIMER
--------------------------------------------------------------------------------------------
De
informatie in deze e-mail en de meegestuurde bestanden zijn
vertrouwelijk en mogelijk wettig beschermd. De e-mail is uitsluitend
bedoeld voor gebruik door de geadresseerde en andere geautoriseerde
ontvangers. Indien u niet de geadresseerde bent, maken wij er u op
attent dat gebruik van de informatie in de e-mail en de meegezonden
bestanden, waaronder openbaarmaking, vermenigvuldiging, verspreiding
en/of verstrekking aan derden niet is toegestaan en mogelijk zelfs
onwettig. Mocht u deze e-mail abusievelijk hebben ontvangen, dan vragen
wij u de afzender op de hoogte te brengen en het originele bericht te
vernietigen. De zender is niet verantwoordelijk voor de inhoud van deze
e-mail en wijst iedere aansprakelijkheid af voor en/of in verband met
alle gevolgen en/of schade van een onjuiste of onvolledige verzending
en/of vertraging ervan. De zender is niet verantwoordelijk voor
meegestuurde virussen. Het is uw eigen verantwoording om e-mails en de
meegezonden bestanden hierop te scannen. Aan deze e-mail kunnen geen
rechten worden ontleend. Belangrijke afspraken of contracten dienen
altijd door de daarvoor bevoegde personen te worden
ondertekend.
---------------------------------------------------------------------------------------------------------------------------------------------------------


Links:
------
[1]
https://github.com/ganoninc/trident-kloader-updated/issues/43#issuecomment-275831942
[2]

**Comment by deus187** [comment]
[iPad2,5_9.3.5(13G36)_000002FB2E182D2A(3277833383210).zip](https://github.com/ganoninc/trident-kloader-updated/files/736854/iPad2.5_9.3.5.13G36._000002FB2E182D2A.3277833383210.zip)

here is the original file, the password is the abbreviation (abréviation) for the dutch word for password.

just to make it easy for ya..

**Comment by qyorwork** [comment]
What is this? a Firmware key?

**Comment by deus187** [comment]
qyorwork schreef op 2017-01-29 02:01: 

> What is this? a Firmware
key? 
> 
> --
> You are receiving this because you authored the
thread.
> Reply to this email directly, view it on GitHub [1], or mute
the thread [2].

shsh blob = https://en.wikipedia.org/wiki/SHSH_BLOB


-- 

---------------------------------------------- DISCLAIMER
--------------------------------------------------------------------------------------------
De
informatie in deze e-mail en de meegestuurde bestanden zijn
vertrouwelijk en mogelijk wettig beschermd. De e-mail is uitsluitend
bedoeld voor gebruik door de geadresseerde en andere geautoriseerde
ontvangers. Indien u niet de geadresseerde bent, maken wij er u op
attent dat gebruik van de informatie in de e-mail en de meegezonden
bestanden, waaronder openbaarmaking, vermenigvuldiging, verspreiding
en/of verstrekking aan derden niet is toegestaan en mogelijk zelfs
onwettig. Mocht u deze e-mail abusievelijk hebben ontvangen, dan vragen
wij u de afzender op de hoogte te brengen en het originele bericht te
vernietigen. De zender is niet verantwoordelijk voor de inhoud van deze
e-mail en wijst iedere aansprakelijkheid af voor en/of in verband met
alle gevolgen en/of schade van een onjuiste of onvolledige verzending
en/of vertraging ervan. De zender is niet verantwoordelijk voor
meegestuurde virussen. Het is uw eigen verantwoording om e-mails en de
meegezonden bestanden hierop te scannen. Aan deze e-mail kunnen geen
rechten worden ontleend. Belangrijke afspraken of contracten dienen
altijd door de daarvoor bevoegde personen te worden
ondertekend.
---------------------------------------------------------------------------------------------------------------------------------------------------------


Links:
------
[1]
https://github.com/ganoninc/trident-kloader-updated/issues/43#issuecomment-275886371
[2]

**Comment by ganoninc** [comment]
IOS 9.3.5 is the latest available version for your iPad. It's not useful to save shsh blobs for that version because Apple will deliver them for ever.
