### ISSUE TITLE
iPad 3,3 9.3.2

### ISSUE THREAD

**Issue by TheMorc** [ganoninc/trident-kloader-updated#44]
i opened an issue on original version about app dont working ane then checking and replying that it w00t roots but when i tried this one with kloader the app like freezes, it works but after some minutes i see old time on new time at status bar. I should again chech if i didint messed something up but i dont know. I saw the issues/experiences at readme.md

**Comment by EGYbkgo9449** [comment]
Can you post your Xcode log please ???

**Comment by Xernium** [comment]
Closed due to no response
