### ISSUE TITLE
odysseusOTA on windows 10

### ISSUE THREAD

**Issue by Pierr0t07** [ganoninc/trident-kloader-updated#5]
Have the same iPad as you 
I follow your mini guide, trident installed, i got the "w00t root" message and the vertical green light.
So i have now my iPad in sleep mode and iTunes tells me that my iPad is in recovery so i think it's ok.
But now im stuck i dont know how to use odysseusOTA cause there is no .exe files in the folder ([http://dayt0n.github.io/odysseus/odysseus-0.999.zip](url)). 

If you can tell me how you use "idevicerestore -e iPad2,1_6.1.3_10B329_Restore.ipsw"?
thanks

**Comment by ganoninc** [comment]
Your iPad is in a good state, wait a minute, I'm searching for odysseus for Windows.

**Comment by ganoninc** [comment]
Maybe that: https://www.youtube.com/watch?v=sNbgmLcFnPg 

Bonus, the video should explain how to use it.

**Comment by Pierr0t07** [comment]
thanks for the link. I try it but i got an error : 
![capturecommand](https://cloud.githubusercontent.com/assets/24977413/21744208/7824ae9a-d511-11e6-8bd6-1c984412b284.PNG) 
:/

**Comment by Pierr0t07** [comment]
I try with an other odysseus for windows and i got this : 
![capturecmd](https://cloud.githubusercontent.com/assets/24977413/21744277/725c8d60-d512-11e6-859b-c1c690815925.PNG)
Maybe it can help you to find the problem.

**Comment by ganoninc** [comment]
Humm, I don't know :/ 

Can you try with the version provided here: https://www.reddit.com/r/jailbreak/comments/5lakuy/tutorial_easy_downgrade_for_iphone_4s_from_933_to/ ?

**Comment by Pierr0t07** [comment]
yes i already try this but i have the same errors when i use "idevicerestore.exe" from libimobiledevice

**Comment by ganoninc** [comment]
Do you have another computer? ^^'

**Comment by Pierr0t07** [comment]
no i dont have :/ 
Anyway thank you for your help ;)
I'll wait maybe another another tools will fix my problem

**Comment by Pierr0t07** [comment]
Problem solved :
[https://github.com/ganoninc/trident-kloader-updated/issues/6](url)

**Comment by Xernium** [comment]
Okay whats wrong this time?
