### ISSUE TITLE
Request for Support of iPad 4 Wifi running on 9.3.3 (iPad 3, 4)

### ISSUE THREAD

**Issue by Spartinus** [ganoninc/trident-kloader-updated#51]
Model A1458 MD511LL/A
Version 9.3.3 (13G34)

I would really appreciate it :) Thank you!

**Comment by Xernium** [comment]
The iPad 4 does not have released keys for said firmware so supporting the device will be a challenge so don't expect to have fast release

**Comment by Spartinus** [comment]
Oh okay :/ I did not know that. Thank you for letting me know. Hopefully one will eventually come out
