### ISSUE TITLE
Off topic- but need answer

### ISSUE THREAD

**Issue by Chasewhip8** [ganoninc/trident-kloader-updated#53]
what are the kernel cache decryption keys for ios 9.3.3 for a ipod 5,1

**Comment by ganoninc** [comment]
Unfortunatly they have not been released (https://www.theiphonewiki.com/wiki/Firmware_Keys/9.x)

**Comment by Chasewhip8** [comment]
Then how did kjc add support for there 32 bit jailbreak for ipod 5,1 9.3.2 and 9.3.4

**Comment by Xernium** [comment]
he used the iPad offsets because the layout of them is similar

**Comment by Chasewhip8** [comment]
Which iPad

**Comment by Chasewhip8** [comment]
And are they exactly simular
