### ISSUE TITLE
Add Support using These Offsets ??

### ISSUE THREAD

**Issue by modularshrimp** [ganoninc/trident-kloader-updated#58]
hi there, A developer found these offsets for ipad 2,7 ios 9.3.1 for home depot jailbreak for 32 bit devices
[find_OSSerializer_serialize()]-0x31812c
[find_OSSymbol_getMetaClass()]-0x31a934
[find_calend_gettime()]-0x1e170
[find_bufattr_cpx()]-0xd9848
[find_clock_ops()]-0x403428
[find_copyin()]-0xc76b4
[find_bx_lr()]-0xd984a
[find_write_gadget()]-0xc73e8
[find_vm_kernel_addrperm()]-0x455844
[find_kernel_pmap()]-0x3f6454
[find_invalidate_tlb()]-0xc7440
[allproc]-0x45717c
[proc_ucred]-0xa4

Is it possible to add downgrade support using these offsets ?? because i want to go back to ios 6 more than jailbreaking

**Comment by ganoninc** [comment]
The iPad mini was sold with iOS 6 at the beginning so it can't be downgraded using this method, only devices sold with iOS 5 can be downgraded.

You'd better jailbreak and try to run iOS 6 with https://coolbooter.com/.
