### ISSUE TITLE
Windows downgrade alternative method + Ipad2,1 IOS 9.3.1 ERRORS

### ISSUE THREAD

**Issue by ghost** [ganoninc/trident-kloader-updated#6]
I dont know whats going wrong ,but i am see w00root ,and sometimes the green vertical line sometimes blinking ,but I cant restore the device . I dont have scp/ftp access to device and no terminal found on screen. I have missing directions how to use the project on X code i dont know how to do it . I am stack on IBEC or iBSS or waiting for device etc. I am shure that i missing some instructions to use all thaat tools ,but maybe the compiled trident .ipa not work corectly on my IOS version. If i can help, Please tell me, I dont know lot but i will try my best .

**Comment by ganoninc** [comment]
If you see the green line, the next step is to use libmobiledevice to put your device in sleep mode (after that your screen will be black and iTunes should say an iPad in recovery mode was found, so you should quit iTunes)

After that is the final step, use idevicerestore


Did you read the Readme ?

What computer do you have ? A Mac, a Linux PC or a Windows PC?

**Comment by ghost** [comment]
Thanks for your help! 
Yes, I am read it ,but this libi mobile device not work for me. Must i make custom frimware or use stock one?
Must i use Odysseus ota on Mac? May i need tiny umbrella TSS Server? I can work on any Platform ,But i am new on this , please forgive me ,for all that questions...
Please i am do this steps : 
1) I use the ipa that is provided here,
2) I am see the green line
3) I am put the device on deep sleep
4) i am open the device again from power button for 5-7 seconds 
5) When use libimobiledevice or odysseus ota i am encounter problems here.

**Comment by ghost** [comment]
I will do it again to tell you the errors i am receive

**Comment by ganoninc** [comment]
Since your iPad is a Wifi Only model, you don't need to build a custom IPSW, you can use the stock one.

On the step 3 of your list, your screen's device should turn black after using libmobiledevice with the sleep command. 
Step 4 shouldn't exist. You don't have to touch your iPad once the screen is black. You can open iTunes to check if your iPad is detected as in recovery mode, but after that, don't forget to quit completely iTunes. 

Step 5, try to restore your device with odysseus ota

**Comment by ghost** [comment]
now i am on windows and the ipad is detected!
Can i use this ? https://github.com/Sn0wCooder/odysseusota-windows ?
We need only the comand listed here?

**Comment by ghost** [comment]
I am get tss server errors

**Comment by ghost** [comment]
I will try on Mac with custom frimware...

**Comment by ganoninc** [comment]
Actually you can follow the command listed above, if you build a custom IPSW, it won't arm your iPad so try ^^

You can jump "6. run kloader and enter in pwned DFU mode" because your iPad is already in pwned DFU mode thanks to the IPA of this repo.

**Comment by ghost** [comment]
Ok i try on mac Virtual machine but with no luck . I have an old mac with 10.7 install i will try there

**Comment by ghost** [comment]
Sadly I am get segmentation fault on 10.7 System . Any way to downgrade on windows?

**Comment by ganoninc** [comment]
https://www.reddit.com/r/jailbreak/comments/5lakuy/tutorial_easy_downgrade_for_iphone_4s_from_933_to/?st=IXOKUQFQ&sh=1e6f07fe

Check that, it works on Windows.

**Comment by ghost** [comment]
Woooooooooooorks!!!! Thanks For all , and for your help!

**Comment by ghost** [comment]
From deep sleep mode
I am use behind to make custom frimware . 
Then i am exit behind 
I am then use the 365 tv frimware manager from Geosn0w and i am check only the custom frimware
then i am click restore and all works perfectly 

Thanks to all developers Perfect work ! now i am feel the speed Again!

**Comment by ganoninc** [comment]
Welcome back to the glorious age of your iPad 2 \o/

**Comment by guzi74** [comment]
Thank you all for this excelent work. I´ve just got restored an Ipad 2,2 9.3.3 to 6.1.3 in 15 minutes.

Good work!

**Comment by ganoninc** [comment]
You're welcome :)

**Comment by Pierr0t07** [comment]
Thank you guys that work perfectly !!!!!!!
