### ISSUE TITLE
iPhone5,4 iOS 9.1 Not supported

### ISSUE THREAD

**Issue by Limon93** [ganoninc/trident-kloader-updated#61]
Iphone 5c GSM Version on iOS 9.1, app reports device not supported.
Thanks for your time.

**Comment by Xernium** [comment]
the 5,4 is supported on 9.1, you probably downloaded an old version.

**Comment by Limon93** [comment]
Used Trident+kloader 1.2.5.ipa
Probably OTA updated.

**Comment by Xernium** [comment]
does not matter. try to use HomeDepot http://wall.supplies
