### ISSUE TITLE
..but how it works on A5X, A6, and A6X iDevices ?

### ISSUE THREAD

**Issue by RichyElBoss** [ganoninc/trident-kloader-updated#63]
This project it’s fine, but I do not really understand how it works on devices that aren’ t iPhone 4s and iPad 2. It works with, or without SHSH? And what is the procedure I must do?

**Comment by Xernium** [comment]
The project supports A5X-A6X because they are 32-bit-based processors. Kloader works with any 32-bit device given you have tfp0 enabled. If you need help downgrading contact me on Twitter `@DjSn0wfall` instead.
