### ISSUE TITLE
iPhone5,4 on 9.3.3 not supported

### ISSUE THREAD

**Issue by nikkisantoro** [ganoninc/trident-kloader-updated#65]
Hello,

I have an iPhone 5C Global (iPhone5,4) on 9.3.3 (13G34) and when I install and run Trident, it says "iPhone5,4  - iOS 9.3.3 (not supported)".

Any help?

Thanks!
Nikki

**Comment by EGYbkgo9449** [comment]
The offsets haven't been added yet, if you can get them make a pull request and we'll add support, or wait for others to get them.

EDIT: I'm sorry my mistake, it's already supported and it should work, can you message me on Twitter so we can solve it ??? @BestTube_YT

**Comment by EGYbkgo9449** [comment]
You've used v1.2.5 (pre-compiled) IPA which doesn't support your device, you have to either wait for someone to compile a new version or compile it yourself.

Closed.
